"""Add canny webook event.

Revision ID: 87ea067084cd
Revises: 9e7246acdff9
Create Date: 2021-11-05 01:23:01.104575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87ea067084cd'
down_revision = '9e7246acdff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_event_cannys',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('event_obj', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_event_cannys_event_type'), 'webhook_event_cannys', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_event_cannys_id'), 'webhook_event_cannys', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_event_cannys_object_type'), 'webhook_event_cannys', ['object_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_event_cannys_object_type'), table_name='webhook_event_cannys')
    op.drop_index(op.f('ix_webhook_event_cannys_id'), table_name='webhook_event_cannys')
    op.drop_index(op.f('ix_webhook_event_cannys_event_type'), table_name='webhook_event_cannys')
    op.drop_table('webhook_event_cannys')
    # ### end Alembic commands ###
