

def clean_discord_handle(handle):
    return handle.\
        replace("#", '').\
        replace("@", '').\
        replace("/", '').\
        replace("!", '').\
        replace("%", '').\
        replace("(", '').\
        replace(")", '').\
        replace("^", '').\
        replace("[", '').\
        replace("]", '').\
        replace("{", '').\
        replace("}", '').\
        replace("|", '').\
        replace("~", '').\
        replace("`", '').\
        replace("'", '').\
        replace('"', '').\
        replace(';', '').\
        replace(':', '').\
        replace('+', '').\
        replace('=', '').\
        replace('*', '').\
        replace('>', '').\
        replace('<', '').\
        replace(',', '')
